# Generated by Django 3.2.16 on 2023-12-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_aianswer_usermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='messenger',
            field=models.CharField(default='Added before model', max_length=255),
        ),
    ]
