# Generated by Django 3.2.16 on 2023-12-18 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_chatuser_messenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aianswer',
            old_name='response_text',
            new_name='message_text',
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='messenger',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='AllMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.chatuser')),
            ],
        ),
        migrations.AlterField(
            model_name='aianswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.allmessages'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.allmessages'),
        ),
    ]
