# Generated by Django 3.2.16 on 2023-12-18 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20231218_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmessages',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.chatuser'),
        ),
    ]
