# Generated by Django 3.2.16 on 2023-12-18 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_allmessages_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
        migrations.AlterField(
            model_name='aianswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.chatuser'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.chatuser'),
        ),
        migrations.DeleteModel(
            name='AllMessages',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
