# Generated by Django 3.2.16 on 2023-12-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_aianswer_ai_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='messenger_id',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
