# Generated by Django 3.2.16 on 2023-12-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_chatuser_messenger_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='last_name',
            field=models.CharField(default='no_last_name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
